# Generated by Django 3.0.5 on 2020-04-09 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gato',
            name='nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gato',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gato',
            name='raza',
            field=models.CharField(blank=True, choices=[('C', 'Callejero'), ('A', 'Angora'), ('S', 'Siames')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='gato',
            name='sexo',
            field=models.CharField(blank=True, choices=[('F', 'Femenino'), ('M', 'Masculino')], max_length=100, null=True),
        ),
    ]
